# NumPy and Pandas Practice Problems (Assignment_1)

---




# NumPy

## 1. Import libraries and Create an array using Numpy

      Expected output:-
      [0 1 2 2 3 4 5 10]

In [ ]:
## YOUR ANSWER:-
import numpy as np
array = np.array([0, 1, 2, 2, 3, 4, 5, 10])
print(array)

[ 0  1  2  2  3  4  5 10]



## 2. Using NumPy get the unique elements of the array

        Expected output :-   
        [0 1 2 3 4 5 10]



In [ ]:
## Your Answer :-
unique_elements = np.unique(array)
print(unique_elements)

[ 0  1  2  3  4  5 10]


## 3. Generate an array of 5 equally spaced points between 0 and 20.

      Expected output :- [0 5. 10. 15. 20.]


In [ ]:
## Your Answer :-
spaced_points = np.linspace(0, 20, 5)
print(spaced_points)

[ 0.  5. 10. 15. 20.]


## 4. Create a 2D array and sort it along first axis and last axis

Sample array-[[4,9],[2,1]]

    Expected output :-

    [[2,1],
    [4,9]]

    [[4,9],
    [1,2]]

In [ ]:
## Your Answer:-
array_2d = np.array([[4, 9], [2, 1]])
sorted_first_axis = np.sort(array_2d, axis=0)
sorted_last_axis = np.sort(array_2d, axis=1)
print(sorted_first_axis)
print(sorted_last_axis)

[[2 1]
 [4 9]]
[[4 9]
 [1 2]]


## 5. Create a NumPy 1D array with numbers from 1 to 10 using np.arange()
      Expected output :-
      [1,2,3,4,5,6,7,8,9,10]

In [ ]:
## Your Answer :-
array_1d = np.arange(1, 11)
print(array_1d)

[ 1  2  3  4  5  6  7  8  9 10]


## 6. Reshape the previous array into 2x5 and perform element-wise multiplication with the sorted array (first axis)

Arrays= [[2,1],[4,9]]   ;  [1,2,3,4,5,6,7,8,9,10]

        Expected output :-

        [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]] *(Reshaped array)*
        
        [[  8,  11,  14,  17,  20],
        [ 58,  71,  84,  97, 110]] *(Multplied array)*




In [ ]:
## Your Answer
reshaped_array = array_1d.reshape(2, 5)
sorted_array = np.array([[2, 1], [4, 9]])
sorted_array_first_axis = np.sort(sorted_array, axis=0)

multiplied_array = reshaped_array * sorted_array_first_axis
print(reshaped_array)
print(multiplied_array)

ValueError: operands could not be broadcast together with shapes (2,5) (2,2) 

# 7. From the Multiplied array get the elements as follows :-

Array=  [[  8,  11,  14,  17,  20],
    [ 58,  71,  84,  97, 110]]

          Expected output :-
          A. [14]
          B. [14,17]
          C. [84,97]
          D. [[14,17],
             [84,97]]







In [ ]:
## Your Answer :-
multiplied_array = np.array([[ 8, 11, 14, 17, 20], [ 58, 71, 84, 97, 110]])

A = multiplied_array[0, 2]
B = multiplied_array[0, 2:4]
C = multiplied_array[1, 2:4]
D = multiplied_array[:, 2:4]

print("A:", A)
print("B:", B)
print("C:", C)
print("D:", D)

A: 14
B: [14 17]
C: [84 97]
D: [[14 17]
 [84 97]]


## 8. Concatenate the original Array in previous one along with array formed in D along axis=1.

      Expected output :-
      conc_arr:
      [[  8  11  14  17  20   2   3]
      [ 58  71  84  97 110   8   9]]


In [ ]:
# Your Answer
concatenated_array = np.concatenate((multiplied_array, D), axis=1)
print(concatenated_array)

[[  8  11  14  17  20  14  17]
 [ 58  71  84  97 110  84  97]]


## 9. Write a NumPy program to count the occurrence of a specified item in a given NumPy array.



        Original array:
        [0,0,0,0,1,2,2,2,2,2,2,2,3,3,3]

        Expected Output:-
        [4,1,7,3]

In [ ]:
## Your Answer :-
original_array = np.array([0,0,0,0,1,2,2,2,2,2,2,2,3,3,3])
unique, counts = np.unique(original_array, return_counts=True)
occurrence_count = dict(zip(unique, counts))
print(list(occurrence_count.values()))

[4, 1, 7, 3]


### 10. Write a NumPy program to remove nan values from a given array.



        Original array:
        [200. 300. nan nan nan 700.]

        After removing nan values:
        [200. 300. 700.]

In [ ]:
## Your Answer :-
original_array_with_nan = np.array([200., 300., np.nan, np.nan, np.nan, 700.])
cleaned_array = original_array_with_nan[~np.isnan(original_array_with_nan)]
print(cleaned_array)

[200. 300. 700.]


## 11. Write a NumPy program to find indices of elements equal to zero in a NumPy array.

      Sample Output:

      Original array:
      [1 0 2 0 3 0 4 5 6 7 8]

      Indices of elements equal to zero of the said array:
      [1 3 5]

In [ ]:
## Your Answer
original_array = np.array([1, 0, 2, 0, 3, 0, 4, 5, 6, 7, 8])
zero_indices = np.where(original_array == 0)
print(zero_indices[0])

[1 3 5]




---





# Pandas


### 1. Load CSV file and print the first 10 rows in a good format ###

In [ ]:
import pandas as pd
movies = pd.read_csv('movies.csv')
print(movies.head(10))

      budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
5  258000000  [{"id": 14, "name": "Fantasy"}, {"id": 28, "na...   
6  260000000  [{"id": 16, "name": "Animation"}, {"id": 10751...   
7  280000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
8  250000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
9  250000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            homepage      id  \
0                        http://www.avatarmovie.com/   19995   
1       http://disney.go.com/disneypictures/pirates/     285   
2        http://www.sonypictures.com/movies/spectre/  206647   
3     

### 2. Calculate the total number of null entries per column

In [ ]:
## Your Answer
null_entries= movies.isnull().sum()
print(null_entries)

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64


### 3. Drop the column having more than 30% null entries

In [ ]:
## Your Answer
threshold = 0.3 * len(movies)
movies_dropped = movies.dropna(thresh=threshold, axis=1)
print(movies_dropped.head())

      budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "nam

### 4. Discover the types of each columns and modify release_date to datetime64[ns] data type

In [ ]:
## Your Answeprint(movies.dtypes)
movies['release_date'] = pd.to_datetime(movies['release_date'], errors='coerce')
print(movies.dtypes)

budget                           int64
genres                          object
homepage                        object
id                               int64
keywords                        object
original_language               object
original_title                  object
overview                        object
popularity                     float64
production_companies            object
production_countries            object
release_date            datetime64[ns]
revenue                          int64
runtime                        float64
spoken_languages                object
status                          object
tagline                         object
title                           object
vote_average                   float64
vote_count                       int64
dtype: object


### 5 Find the top 10 movies with the highest budget. Display their titles, budgets, and revenues.

In [ ]:
# Your Answetop_10_budget_movies = movies.nlargest(10, 'budget')[['title', 'budget', 'revenue']]
top_10_budget_movies = movies.nlargest(10, 'budget')[['title', 'budget', 'revenue']]
print(top_10_budget_movies)

                                          title     budget     revenue
17  Pirates of the Caribbean: On Stranger Tides  380000000  1045713802
1      Pirates of the Caribbean: At World's End  300000000   961000000
7                       Avengers: Age of Ultron  280000000  1405403694
10                             Superman Returns  270000000   391081192
4                                   John Carter  260000000   284139100
6                                       Tangled  260000000   591794936
5                                  Spider-Man 3  258000000   890871626
13                              The Lone Ranger  255000000    89289910
3                         The Dark Knight Rises  250000000  1084939099
8        Harry Potter and the Half-Blood Prince  250000000   933959197


### 6  Export the data of movies with a rating above 8.0 and print them in sequenticial order according to names(Only movies name to be printed).

In [ ]:
# Filter movies with a rating above 8.0 and sort them by title
good_movies = movies[movies['vote_average'] > 8.0].sort_values(by='title')['title']

# Print the names of the movies
print(good_movies.to_string(index=False))


                                 12 Angry Men
                           American History X
                         Anne of Green Gables
                                  City of God
                                     Counting
                        Dancer, Texas Pop. 81
                           Dead Poets Society
                                   Fight Club
                                 Forrest Gump
                                   GoodFellas
                             Guten Tag, Ramón
                         Howl's Moving Castle
                                    Inception
                                 Interstellar
                               Little Big Top
                                   Love Jones
                        Me You and Five Bucks
                                      Memento
                                 Modern Times
                  Once Upon a Time in America
                 Once Upon a Time in the West
              One Flew Over the Cu

###  7 Calculate the correlation matrix for numerical columns. Which pairs of features have the highest correlation?


In [ ]:
# Your Code
correlation_matrix = movies.corr()
highest_correlation = correlation_matrix.unstack().sort_values(ascending=False)
highest_correlation_pairs = highest_correlation[highest_correlation < 1.0].head(1)
print(correlation_matrix)
print(highest_correlation_pairs)

ValueError: could not convert string to float: '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

### 8. Identify and fill missing values in the 'runtime' column with the median runtime.

In [ ]:
# Your Code
median_runtime = movies['runtime'].median()
movies['runtime'].fillna(median_runtime, inplace=True)
print(movies['runtime'])

0       162.0
1       169.0
2       148.0
3       165.0
4       132.0
        ...  
4798     81.0
4799     85.0
4800    120.0
4801     98.0
4802     90.0
Name: runtime, Length: 4803, dtype: float64


### 9. Identify and remove duplicate rows based on the title and release_date columns.

In [ ]:
# Your Code
movies_no_duplicates = movies.drop_duplicates(subset=['title', 'release_date'])
print(movies_no_duplicates)

         budget                                             genres  \
0     237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...         ...                                                ...   
4798     220000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4799       9000  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4800          0  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4801          0                                                 []   
4802          0                [{"id": 99, "name": "Documentary"}]   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.

### 10.  Define a function that categorizes movies into 'High Budget' and 'Low Budget' based on whether their budget is above or below the median budget. Apply this function to create a new column budget_category

In [ ]:
# Your Code
median_budget = movies['budget'].median()
movies['budget_category'] = movies['budget'].apply(lambda x: 'High Budget' if x > median_budget else 'Low Budget')
print(movies[['title', 'budget', 'budget_category']])

                                         title     budget budget_category
0                                       Avatar  237000000     High Budget
1     Pirates of the Caribbean: At World's End  300000000     High Budget
2                                      Spectre  245000000     High Budget
3                        The Dark Knight Rises  250000000     High Budget
4                                  John Carter  260000000     High Budget
...                                        ...        ...             ...
4798                               El Mariachi     220000      Low Budget
4799                                 Newlyweds       9000      Low Budget
4800                 Signed, Sealed, Delivered          0      Low Budget
4801                          Shanghai Calling          0      Low Budget
4802                         My Date with Drew          0      Low Budget

[4803 rows x 3 columns]


### 11 Merge the columns 'original_title', 'release_date', and 'popularity' into a single column named 'movie_info'. Then, display only the 'movie_info' column.

In [ ]:
# Your Code
movies['movie_info'] = movies['original_title'] + ', ' + movies['release_date'].astype(str) + ', ' + movies['popularity'].astype(str)
print(movies['movie_info'])

0                          Avatar, 2009-12-10, 150.437577
1       Pirates of the Caribbean: At World's End, 2007...
2                         Spectre, 2015-10-26, 107.376788
3            The Dark Knight Rises, 2012-07-16, 112.31295
4                      John Carter, 2012-03-07, 43.926995
                              ...                        
4798                   El Mariachi, 1992-09-04, 14.269792
4799                      Newlyweds, 2011-12-26, 0.642552
4800      Signed, Sealed, Delivered, 2013-10-13, 1.444476
4801               Shanghai Calling, 2012-05-03, 0.857008
4802              My Date with Drew, 2005-08-05, 1.929883
Name: movie_info, Length: 4803, dtype: object
